sudo: required

language: ruby

services: 
  - docker

before_install:
# #- docker-compose pull
 - docker-compose build
 - docker-compose up -d
 - sleep 45
 - docker-compose ps
 - cd app && bundle install 

script:
 - rspec -f d spec

after_success:
  - docker-compose stop

after_failure:
  - docker-compose stop
  - docker-compose logs
